### ISSUE TITLE
Angelman calculated field error No. 2

### ISSUE THREAD

**Issue by id2359** [muccg/angelman#326]
```
builtins.AttributeError
AttributeError: module 'rdrf.forms.fields.calculated_functions' has no attribute 'ANGBMImetric_inputs'

Traceback (most recent call last)
File "/env/lib/python3.7/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
return self.application(environ, start_response)
File "/env/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
response = self.get_response(request)
File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 78, in get_response
response = self._middleware_chain(request)
File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
response = response_for_exception(request, exc)
File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/env/lib/python3.7/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/env/lib/python3.7/site-packages/six.py", line 692, in reraise
raise value.with_traceback(tb)
File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
return self.dispatch(request, *args, **kwargs)
File "/env/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
return handler(request, *args, **kwargs)
File "/env/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
return bound_method(*args, **kwargs)
File "/env/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/app/rdrf/rdrf/rdrf/views/form_view.py", line 352, in get
context = self._build_context(user=request.user, patient_model=patient_model)
File "/app/rdrf/rdrf/rdrf/views/form_view.py", line 809, in _build_context
Display the sourcecode for this frameOpen an interactive python shell in this frameself.registry, self.registry_form, section_model)
File "/app/rdrf/rdrf/rdrf/views/form_view.py", line 765, in _get_form_class_for_section
user_groups=self.request.user.groups.all())
File "/app/rdrf/rdrf/rdrf/forms/dynamic/dynamic_forms.py", line 72, in create_form_class_for_section
is_superuser=is_superuser).create_field()
File "/app/rdrf/rdrf/rdrf/forms/dynamic/field_lookup.py", line 283, in create_field
field = self._create_field()
File "/app/rdrf/rdrf/rdrf/forms/dynamic/field_lookup.py", line 411, in _create_field
script = parser.get_script()
File "/app/rdrf/rdrf/rdrf/forms/dynamic/calculated_fields.py", line 37, in get_script
func = getattr(mod, f"{self.cde.code}_inputs")
AttributeError: module 'rdrf.forms.fields.calculated_functions' has no attribute 'ANGBMImetric_inputs'
```

**Comment by mouneyrac** [comment]
fixed in https://github.com/muccg/rdrf/issues/921
